---
- name: Creates ec2 instance
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: Create ec2 instance
      ec2:
        key_name: ansible
        instance_type: t2.micro
        image: ami-0323c3dd2da7fb37d
        count: 1
        vpc_subnet_id: subnet-04941aa978de5b6be
        region: us-east-1a
        assign_public_ip: yes