---
- name: Creates ec2 instance
  hosts: localhost
  become: true
  become_method: sudo
  tasks:
    - name: Create ec2 instance
      ec2:
        key_name: bastion
        instance_type: t2.micro
        image: ami-0323c3dd2da7fb37d
        count: 1
        vpc_subnet_id: subnet-0814e75b49b5ce629
        region: eu-west-2a
        assign_public_ip: yes